CREATE TABLE USUARIO(
	IDUSUARIO		UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	LOGIN			NVARCHAR(50)		NOT NULL UNIQUE,
	SENHA			NVARCHAR(40)		NOT NULL,
	DATAINCLUSAO	DATETIME			NOT NULL,
	PRIMARY KEY(IDUSUARIO))
GO

INSERT INTO USUARIO
VALUES(
	NEWID(),
	'Usuário API',
	'usuario_api',
	CONVERT(VARCHAR(32), HASHBYTES('MD5', '@admin2022'), 2),
	GETDATE()
)
GO

SELECT * FROM USUARIO
GO

